CREATE PROCEDURE [dbo].[AARichardussTestCase1] As
  INSERT Richarduss.dbo.CUSTOMERS2 (ID, NAME, AGE, ADDRESS, SALARY)
  SELECT TOP 10 ID, NAME, AGE, ADDRESS, SALARY FROM Richarduss.dbo.CUSTOMERS3
go

