create table DatabaseLog
(
    DatabaseLogID int identity
        constraint PK_DatabaseLog_DatabaseLogID
            primary key nonclustered,
    PostTime      datetime      not null,
    DatabaseUser  sysname       not null,
    Event         sysname       not null,
    [Schema]      sysname,
    Object        sysname,
    TSQL          nvarchar(max) not null,
    XmlEvent      xml           not null
)
go

exec sp_addextendedproperty 'MS_Description',
     'Audit table tracking all DDL changes made to the AdventureWorks database. Data is captured by the database trigger ddlDatabaseTriggerLog.',
     'SCHEMA', 'dbo', 'TABLE', 'DatabaseLog'
go

exec sp_addextendedproperty 'MS_Description', 'Primary key for DatabaseLog records.', 'SCHEMA', 'dbo', 'TABLE',
     'DatabaseLog', 'COLUMN', 'DatabaseLogID'
go

exec sp_addextendedproperty 'MS_Description', 'Primary key (nonclustered) constraint', 'SCHEMA', 'dbo', 'TABLE',
     'DatabaseLog', 'CONSTRAINT', 'PK_DatabaseLog_DatabaseLogID'
go

exec sp_addextendedproperty 'MS_Description', 'Nonclustered index created by a primary key constraint.', 'SCHEMA',
     'dbo', 'TABLE', 'DatabaseLog', 'INDEX', 'PK_DatabaseLog_DatabaseLogID'
go

exec sp_addextendedproperty 'MS_Description', 'The date and time the DDL change occurred.', 'SCHEMA', 'dbo', 'TABLE',
     'DatabaseLog', 'COLUMN', 'PostTime'
go

exec sp_addextendedproperty 'MS_Description', 'The user who implemented the DDL change.', 'SCHEMA', 'dbo', 'TABLE',
     'DatabaseLog', 'COLUMN', 'DatabaseUser'
go

exec sp_addextendedproperty 'MS_Description', 'The type of DDL statement that was executed.', 'SCHEMA', 'dbo', 'TABLE',
     'DatabaseLog', 'COLUMN', 'Event'
go

exec sp_addextendedproperty 'MS_Description', 'The schema to which the changed object belongs.', 'SCHEMA', 'dbo',
     'TABLE', 'DatabaseLog', 'COLUMN', 'Schema'
go

exec sp_addextendedproperty 'MS_Description', 'The object that was changed by the DDL statment.', 'SCHEMA', 'dbo',
     'TABLE', 'DatabaseLog', 'COLUMN', 'Object'
go

exec sp_addextendedproperty 'MS_Description', 'The exact Transact-SQL statement that was executed.', 'SCHEMA', 'dbo',
     'TABLE', 'DatabaseLog', 'COLUMN', 'TSQL'
go

exec sp_addextendedproperty 'MS_Description', 'The raw XML data generated by database trigger.', 'SCHEMA', 'dbo',
     'TABLE', 'DatabaseLog', 'COLUMN', 'XmlEvent'
go

